# Generated by Django 6.0.3 on 2026-04-12 00:00

import app.users.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("iso_2", models.CharField(db_index=True, max_length=2, unique=True)),
                ("iso_phone_code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, default="", max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("msisdn", models.CharField(db_index=True, max_length=20, unique=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("consent", models.BooleanField(default=False)),
                ("kyc_verified", models.BooleanField(default=False)),
                ("kyc_verified_dt", models.DateTimeField(blank=True, null=True)),
                ("email_notifications", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.country"),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[("objects", app.users.models.UserManager())],
        ),
        migrations.CreateModel(
            name="FailedLoginAudit",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("msisdn", models.CharField(db_index=True, max_length=20)),
                ("device_id", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("failure_reason", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "failed_login_audit",
                "indexes": [models.Index(fields=["msisdn", "created_dt"], name="failed_logi_msisdn_c7c0a4_idx")],
            },
        ),
        migrations.CreateModel(
            name="RegistrationSession",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("msisdn", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("registration_token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("phone_verified", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMAIL_PENDING", "Email Pending"),
                            ("EMAIL_OTP_SENT", "Email OTP Sent"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                        ],
                        default="EMAIL_PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "registration_sessions",
                "indexes": [models.Index(fields=["msisdn", "status"], name="registratio_msisdn_c144b0_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(db_index=True, default=app.users.models.generate_unique_account_id, editable=False, max_length=11, unique=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("in_transfer", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="account", to="users.user"),
                ),
            ],
            options={
                "db_table": "user_accounts",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("device_id", models.CharField(db_index=True, max_length=128)),
                ("ip_address", models.GenericIPAddressField()),
                ("refresh_token_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("state", models.CharField(choices=[("LOCKED", "Locked"), ("UNLOCKED", "Unlocked")], default="UNLOCKED", max_length=20)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.user")),
            ],
            options={
                "db_table": "user_sessions",
                "indexes": [models.Index(fields=["user", "is_active"], name="user_sessio_user_id_bb1b83_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "device_id"), name="unique_user_session")],
            },
        ),
    ]
