# Generated by Django 5.2.12 on 2026-04-06 00:00

from django.db import migrations


def seed_initial_data(apps, schema_editor):
    Country = apps.get_model("users", "Country")

    # Seed Countries
    countries_data = [
        {"name": "Lebanon", "iso_2": "LB", "iso_phone_code": "+961"},
        {"name": "United States", "iso_2": "US", "iso_phone_code": "+1"},
        {"name": "United Kingdom", "iso_2": "GB", "iso_phone_code": "+44"},
        {"name": "Canada", "iso_2": "CA", "iso_phone_code": "+1"},
        {"name": "Australia", "iso_2": "AU", "iso_phone_code": "+61"},
        {"name": "Germany", "iso_2": "DE", "iso_phone_code": "+49"},
        {"name": "France", "iso_2": "FR", "iso_phone_code": "+33"},
        {"name": "Japan", "iso_2": "JP", "iso_phone_code": "+81"},
        {"name": "India", "iso_2": "IN", "iso_phone_code": "+91"},
        {"name": "Brazil", "iso_2": "BR", "iso_phone_code": "+55"},
    ]
    for country_data in countries_data:
        Country.objects.create(**country_data)


def reverse_seed_initial_data(apps, schema_editor):
    Country = apps.get_model("users", "Country")
    Country.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, reverse_seed_initial_data),
    ]
