# Generated by Django 6.0.3 on 2026-04-12 00:00

import app.wallets.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("wallet_id", models.CharField(db_index=True, default=app.wallets.models.generate_unique_wallet_id, editable=False, max_length=11, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("in_transfer", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("is_main", models.BooleanField(db_index=True, default=False)),
                (
                    "user_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wallets", to="users.useraccount"),
                ),
            ],
            options={
                "db_table": "wallets",
                "indexes": [
                    models.Index(fields=["user_account", "is_active"], name="wallets_user_ac_896dc2_idx"),
                    models.Index(fields=["user_account", "is_main"], name="wallets_user_ac_6abc78_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_account", "name"), name="unique_wallet_name_per_account"),
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)),
                        fields=("user_account", "is_main"),
                        name="unique_main_wallet_per_account",
                    ),
                ],
            },
        ),
    ]
