# Generated by Django 6.0.3 on 2026-04-12 00:00

import app.transactions.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(db_index=True, default=app.transactions.models.generate_unique_tx_id, editable=False, max_length=11, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("transaction_type", models.CharField(choices=[("TRANSFER", "Transfer"), ("TOP_UP", "Top-Up")], max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("stripe_session_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("payment_method_id", models.CharField(blank=True, max_length=255, null=True)),
                ("card_brand", models.CharField(blank=True, max_length=20, null=True)),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("reject_reason", models.TextField(blank=True, null=True)),
                ("completed_dt", models.DateTimeField(blank=True, null=True)),
                ("rejected_dt", models.DateTimeField(blank=True, null=True)),
                ("revoked_dt", models.DateTimeField(blank=True, null=True)),
                (
                    "from_wallet",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sent_transactions", to="wallets.wallet"),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="received_transactions", to="wallets.wallet"),
                ),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(fields=["from_wallet", "status"], name="transaction_from_wa_dc0ccc_idx"),
                    models.Index(fields=["to_wallet", "status"], name="transaction_to_wall_edebfc_idx"),
                    models.Index(fields=["status", "created_dt"], name="transaction_status_4b4c3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("POSTED", "Posted"), ("VOIDED", "Voided")], default="PENDING", max_length=10)),
                ("created_dt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ledgers", to="transactions.transaction"),
                ),
                ("user_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.useraccount")),
            ],
            options={
                "db_table": "ledger_entries",
                "indexes": [
                    models.Index(fields=["user_account", "status"], name="ledger_entr_user_ac_d0149a_idx"),
                    models.Index(fields=["transaction", "status"], name="ledger_entr_transac_7c838a_idx"),
                ],
            },
        ),
    ]
